services:
  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    ports:
      - 86:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_TABLE_PREFIX: '${WORDPRESS_TABLE_PREFIX:-wp_}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./wordpress/wp-content/themes:/var/www/html/wp-content/themes
      - ./wordpress/wp-content/uploads:/var/www/html/wp-content/uploads

  database:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    expose:
      - 3307
      - 33070
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}' # somewordpress
      MYSQL_DATABASE: '${MYSQL_DATABASE}' #wordpress
      MYSQL_USER: '${MYSQL_USER}' #wordpress
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}' #wordpress

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8086:80'
    restart: always
    environment:
      PMA_HOST: '${MYSQL_HOST}'
      PMA_USER: root #'${MYSQL_USER}'
      PMA_PASSWORD: '${MYSQL_ROOT_PASSWORD}' #'${MYSQL_PASSWORD}'

networks:
  default:
    name: nginx-proxy
    external: true

volumes:
  db_data:
